<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>900ee664-e54a-4eb1-a87d-e65fe57676af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > i > svg.small.no-margin > use</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>55a8e85b-c1f0-416e-85df-4b3b40122866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/on/demandware.static/Sites-intimissimi-us-Site/-/en_US/v1654099542859/images/sprite.svg#removeproduct</value>
      <webElementGuid>bad06f5e-d27b-4571-bfff-3f77fadf2f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;ls-tab-off fpls-js ae-lang-en ae-device-desktop ae-launcher&quot;]/div[@class=&quot;page page--full&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;cart cart-page grid-x grid-margin-x js-modal-cta-label&quot;]/div[@class=&quot;cell medium-6&quot;]/div[@class=&quot;cart-line-item    product-info  uuid-cea02acb26e011221feef6ebf0 unique-identifier-no&quot;]/div[@class=&quot;line-item-header grid-x grid-margin-x align-right&quot;]/div[@class=&quot;cell small-5 text-right&quot;]/button[@class=&quot;line-item-action remove-btn remove-product btn btn-light ae-button&quot;]/span[1]/i[1]/svg[@class=&quot;small no-margin&quot;]/use[1]</value>
      <webElementGuid>09daa0f5-ead0-465a-bf7d-15c65577eec0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
