<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ich mchte Neuigkeiten und Angebote erh_bba9f0</name>
   <tag></tag>
   <elementGuidId>2b4f3b4b-2c76-47b4-a080-109f70bb8cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div[2]/div[4]/div/div/form/div[2]/div/div[2]/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.boolean-field.no-margin > span.radio-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;ls-tab-off&quot;]/div[@class=&quot;page page--full page--login&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-x align-center full-width-page&quot;]/div[@class=&quot;cell large-7&quot;]/form[@class=&quot;registration registration-step-final&quot;]/div[@class=&quot;form-group error-inside grid-x policy-register-form&quot;]/div[@class=&quot;cell form-group error-inside grid-x&quot;]/div[@class=&quot;cell large-3 small-4 text-right&quot;]/div[@class=&quot;mobile-flex-fields&quot;]/div[@class=&quot;right-align right-align-cell&quot;]/label[@class=&quot;boolean-field no-margin&quot;]/span[@class=&quot;radio-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[2]/div[4]/div/div/form/div[2]/div/div[2]/div/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
