<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>aa650866-168b-4ce0-b2ac-6ab6ebe55d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.geoblock-close-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='geoblock-close']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9659750-614e-4d47-96dc-e05d869cc69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>geoblock-close-text</value>
      <webElementGuid>760a7cad-b32c-4f79-b0f9-fc26fbab0b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Esci</value>
      <webElementGuid>b156c398-563f-4ff4-8017-b2933fbc1602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>37f82aa0-db3e-42a0-9c8e-84ca28a7c0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geoblock-close&quot;)/span[@class=&quot;geoblock-close-text&quot;]</value>
      <webElementGuid>95ceeca2-703d-43fe-9914-d64c5a095147</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='geoblock-close']/span</value>
      <webElementGuid>85effd86-16bc-4762-af7e-018ecbc78248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Visita l', &quot;'&quot;, 'e-store del tuo paese')])[1]/following::span[2]</value>
      <webElementGuid>5915183e-0717-431e-93bc-a3b9217eab07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'geoblock-close', '&quot;', ')/span[@class=', '&quot;', 'geoblock-close-text', '&quot;', ']')])[1]/preceding::span[1]</value>
      <webElementGuid>2aea35b7-7c9e-4c0d-afde-90be0d72e4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>7890fe46-8fb1-48f6-897c-ce8561ea5948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>2f15dc02-f85e-47b5-9de2-42a0c84bac27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
