<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept Cookies</name>
   <tag></tag>
   <elementGuidId>130f60be-953d-4523-b1f9-f853d0e475c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='acceptAllButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acceptAllButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06efcc3d-e929-469c-8bf1-8e24d48fcb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptAllButton</value>
      <webElementGuid>552ab55f-0706-4e7e-a2cf-fd2aac0bfd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gdpr_btn gdpr_btn_reversed gdprCookieBanner_button gdprCookieBanner_button-custom</value>
      <webElementGuid>92a08c83-436b-41d3-880c-fca4ab95873b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pagename</name>
      <type>Main</type>
      <value>PayPal Checkout|acceptcookies</value>
      <webElementGuid>c19f6630-fba8-4239-9f12-544c1274c86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>04bb98f7-5a37-4d92-adf9-6ac3cdd895d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept Cookies</value>
      <webElementGuid>7c0e343d-48fe-492e-81c8-f1b755051831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptAllButton&quot;)</value>
      <webElementGuid>dad6c545-717d-4637-9f4b-d7bdb075cf0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='acceptAllButton']</value>
      <webElementGuid>2800a1fa-d5d8-43cb-8d96-8370fab0a75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gdprCookieContent_wrapper']/div/div/button</value>
      <webElementGuid>09006947-1dcc-4cf1-9703-67e29f39a36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage your cookies'])[1]/following::button[1]</value>
      <webElementGuid>f3319960-80e4-41ae-9154-7e408ecd53f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/following::button[1]</value>
      <webElementGuid>3901c610-8c83-4cc1-a77c-0ea939bbf152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'acceptAllButton', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>d6521c90-5b15-4410-bc47-bd6bbd3870b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept Cookies']/parent::*</value>
      <webElementGuid>93956b15-f7d5-40ce-aaed-f4be2640f198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button</value>
      <webElementGuid>6b3892ba-c0cc-4dc9-bd65-c9fda38c190b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'acceptAllButton' and (text() = 'Accept Cookies' or . = 'Accept Cookies')]</value>
      <webElementGuid>ada42084-cc13-4b91-b486-fe049d04452a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
