<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vedi carrello</name>
   <tag></tag>
   <elementGuidId>4fe9b3e5-9c16-4dd7-9bc4-1be492bc7b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='checkout-button-secure-checkout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkout-button-secure-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e97584c2-7311-4452-868c-8866761bc3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-button-secure-checkout</value>
      <webElementGuid>737d6c45-dcd4-4c6f-a4b8-998049f46f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://test.falconeri.com/it/cart/</value>
      <webElementGuid>ff65c741-0a2c-4718-9663-ebfc2574060e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button extended uppercase button-black minicart-checkout-button</value>
      <webElementGuid>e9295265-741e-4593-ac4d-12b5be9d113b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39eea655-80b4-4a5f-8ac7-85463b63cbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bfa495be-c3ab-410f-992f-f505993f51c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Vedi carrello
</value>
      <webElementGuid>52d1656b-1238-4006-8a17-e9248114eb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;fpls-js ls-tab-off minicart-is-open&quot;]/div[@class=&quot;page&quot;]/header[@class=&quot;main-header&quot;]/nav[@class=&quot;solid&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-x align-middle&quot;]/div[@class=&quot;main-header-wrap secondary-menu-wrap cell large-5 auto large-order-3 small-order-2&quot;]/div[@class=&quot;ico-header-menu&quot;]/div[@class=&quot;main-header-login first-level navigation&quot;]/div[@class=&quot;minicart open&quot;]/div[@class=&quot;popover popover-bottom show&quot;]/div[@class=&quot;bottom-box-fixed&quot;]/div[@class=&quot;grid-x estimated-total hide-for-small-only&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;cell&quot;]/a[@id=&quot;checkout-button-secure-checkout&quot;]</value>
      <webElementGuid>2a4286bc-0655-4f57-9235-c4b409432f95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='checkout-button-secure-checkout']</value>
      <webElementGuid>f416d8b1-a4f9-43ab-a4c2-bd34fa862b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[4]/header/nav/div/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>a1b9a3ff-f1bc-4298-9c0a-9a449bdd4449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vedi carrello')]</value>
      <webElementGuid>182b47c8-9655-4577-b765-69a6b7037953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€591.00'])[1]/following::a[1]</value>
      <webElementGuid>6ec5789f-9b2f-4677-a2fc-7ea60633d5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iva inclusa'])[1]/following::a[1]</value>
      <webElementGuid>6ce2a969-1cc2-4983-b445-885399680ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impossibile aggiungere il prodotto'])[1]/preceding::a[1]</value>
      <webElementGuid>2320a821-58fa-45e5-b240-68588d2f26d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancella'])[1]/preceding::a[1]</value>
      <webElementGuid>4ed5e656-adf9-49a4-820c-21c7146d16e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vedi carrello']/parent::*</value>
      <webElementGuid>a57a17fc-aef9-4d55-a826-d53e7a2dd15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://test.falconeri.com/it/cart/')]</value>
      <webElementGuid>30baa8f7-28b1-4af5-95db-729b35e45766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>d627ce9b-c4f0-429e-b293-1d56b8e26643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'checkout-button-secure-checkout' and @href = 'https://test.falconeri.com/it/cart/' and (text() = '
Vedi carrello
' or . = '
Vedi carrello
')]</value>
      <webElementGuid>d40258b6-4a7e-4e85-a370-6a17511b7e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
