<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aggiungi al carrello</name>
   <tag></tag>
   <elementGuidId>faf3d8da-120a-4fd6-9f99-4d2761e8b409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='descriptionSidebar']/div/div[5]/div[4]/div/div/button[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.addtocart-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8013191f-34ee-4a60-a09d-389458e81fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addtocart-text</value>
      <webElementGuid>e187d735-54fa-475a-b08f-9348f84ad7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aggiungi al carrello</value>
      <webElementGuid>54ff7b55-6369-4fb3-9287-774b43581c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionSidebar&quot;)/div[@class=&quot;cell large-offset-1 large-9 grid-y&quot;]/div[@class=&quot;product-sidebar-section&quot;]/div[@class=&quot;cell add-to-cart-actions show-for-large&quot;]/div[@class=&quot;cart-and-ipay&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/button[@class=&quot;cell auto add-to-cart button button-addtocart&quot;]/span[@class=&quot;addtocart-content-text&quot;]/span[@class=&quot;addtocart-text&quot;]</value>
      <webElementGuid>d1782b31-c34d-41e7-b718-e1470c778cc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='descriptionSidebar']/div/div[5]/div[4]/div/div/button[2]/span/span</value>
      <webElementGuid>1f3d5450-f3f2-4522-b3c4-056de13824ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerca in negozio'])[1]/following::span[2]</value>
      <webElementGuid>39c9cad9-0d72-4502-88e1-7995104d9f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::span[2]</value>
      <webElementGuid>a6678053-4317-4cb2-859b-69070063fa9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizza'])[6]/preceding::span[2]</value>
      <webElementGuid>60d2f4ed-4568-4f16-9b4e-f2be5c512b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleziona una taglia:'])[1]/preceding::span[2]</value>
      <webElementGuid>387117d0-f33d-4fdf-8fa5-001841109fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aggiungi al carrello']/parent::*</value>
      <webElementGuid>f5ddf3da-9156-44e3-9503-322ba6e1378f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>c1ec084d-ac87-4249-a03f-f3a0d581a8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Aggiungi al carrello' or . = 'Aggiungi al carrello')]</value>
      <webElementGuid>3c56dc11-c261-4142-99f6-7b4491a83d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
