<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clzSelectPPUS</name>
   <tag></tag>
   <elementGuidId>36048ed7-e372-406f-bb04-c641e5b0efb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[1]/div[2]/div/div[1]/div[12]/div[2]/form/fieldset/div[2]/ul/div[4]/div[1]/label/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
