<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Damen_prehome-img hide-for-small-only</name>
   <tag></tag>
   <elementGuidId>33fb90eb-a88b-49d2-a27f-858cfc221369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.prehome-img.hide-for-small-only</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='catWoman']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6e9cf3ef-938f-4b79-a586-1f066fe17813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prehome-img hide-for-small-only</value>
      <webElementGuid>90543079-2505-462c-b895-d6726c61cbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg</value>
      <webElementGuid>526ac33e-e909-4cb6-846f-76d009fb45c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catWoman&quot;)/a[1]/img[@class=&quot;prehome-img hide-for-small-only&quot;]</value>
      <webElementGuid>37544c6c-dd5b-4898-b066-56e8e6da9d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d9080173-8645-46e5-af6f-58abefbeabb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prehome-img hide-for-small-only</value>
      <webElementGuid>ea05aa22-63b0-4193-8753-966fdfe09c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg</value>
      <webElementGuid>f4068334-6657-4b4b-9525-9a2e7f3be557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catWoman&quot;)/a[1]/img[@class=&quot;prehome-img hide-for-small-only&quot;]</value>
      <webElementGuid>5db00a26-ad68-4bb2-a262-d35e294a56ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catWoman']/a/img</value>
      <webElementGuid>676f44fb-1d29-4ffb-8da7-adf8e465c6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg')]</value>
      <webElementGuid>706955dc-c340-43ce-bbe1-f62a2fccded8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>81ba4f25-73ac-4948-9413-00b5ac9ba546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg']</value>
      <webElementGuid>92484d3c-9f99-43fc-9cd9-91cc9737808c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
