<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>8566c8b6-68df-4e4b-83ab-aa93db46aaca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.geoblock-close-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='geoblock-close']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2b6b2945-4562-4d6b-aabe-d813a23319e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>geoblock-close-text</value>
      <webElementGuid>b9578b09-1036-4aa9-b002-d67b0f575cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Esci</value>
      <webElementGuid>8d3617f1-04a8-4d5e-9037-bea3ebec0a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>9504cf35-9615-47af-86c6-24851aac92ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geoblock-close&quot;)/span[@class=&quot;geoblock-close-text&quot;]</value>
      <webElementGuid>fddcf7e5-d1d9-4a94-9abc-4c9b4c3e4fac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='geoblock-close']/span</value>
      <webElementGuid>23964504-3efc-4ce2-a9a4-a2b11daff2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Besuche den E-Shop deines Landes:'])[1]/following::span[2]</value>
      <webElementGuid>7eacc631-d766-4e6f-ba46-af525ac4c233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'geoblock-close', '&quot;', ')/span[@class=', '&quot;', 'geoblock-close-text', '&quot;', ']')])[1]/preceding::span[1]</value>
      <webElementGuid>af204294-5d4a-4432-b9dc-1b8e40e5602e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sie haben noch keine Antwort auf Ihre Frage gefunden?'])[1]/preceding::span[1]</value>
      <webElementGuid>8e65fa3d-d04e-4dbb-9c2f-4806ecf9dede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>bf52e4bb-b837-4b0c-969a-4e06f84d98c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>a8f11c72-a655-478a-b05a-5d4a2588eab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
