<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yes1</name>
   <tag></tag>
   <elementGuidId>1bb39b9c-0fb9-4121-ad5e-2172b7544914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div[2]/div/form/div[5]/div[2]/label[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'boolean-field' and @for = 'input-id-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boolean-field</value>
      <webElementGuid>ad050c4f-b530-4e78-a52d-690328b34943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>input-id-1</value>
      <webElementGuid>57e58c2d-5a47-4071-a161-98575be9125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newspromotions</value>
      <webElementGuid>60f769dc-a39c-42b4-9d86-253df8df04db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
