<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Avanti</name>
   <tag></tag>
   <elementGuidId>5c6cec44-7deb-4018-992a-2bc75d243dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnNext']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnNext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51901b17-610d-458a-b9ad-bf7fca7fc07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button actionContinue scTrack:unifiedlogin-login-click-next</value>
      <webElementGuid>c1fe113d-d764-4c00-958b-5174fdbd02b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bf0ebfbf-5c8e-4b9d-8114-1a27f743cee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNext</value>
      <webElementGuid>5ff5d5ec-b558-42bd-a6f5-ccea05e257e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnNext</value>
      <webElementGuid>7e624db9-1306-464a-9fd0-03606233ba47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>c8f3d9c5-7d84-49da-843c-f32e484e5940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>70386521-9393-422e-a76f-8726dacc199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avanti</value>
      <webElementGuid>31cd4a6e-fe0a-4812-8fd5-0bdfaadda273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNext&quot;)</value>
      <webElementGuid>49cc89af-6f36-4b83-a836-69c5eacb152b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnNext']</value>
      <webElementGuid>79e59ad8-0eee-4e3f-8ed9-e9ef6ab0f99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='splitEmail']/div[3]/button</value>
      <webElementGuid>ce949768-bf99-48f6-80e1-4d49cd26e1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulsante audio'])[2]/following::button[1]</value>
      <webElementGuid>78e33aac-c073-4a3b-a435-563230d5fdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ricarica immagine'])[2]/following::button[1]</value>
      <webElementGuid>91c4be3d-5450-431a-874b-e7abf1408b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::button[1]</value>
      <webElementGuid>99a866ad-ed2a-41fc-a8a6-6b7650dd23e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostra password'])[1]/preceding::button[1]</value>
      <webElementGuid>4bf24a95-73a1-4057-bcb7-e5c11f9b3611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Avanti']/parent::*</value>
      <webElementGuid>c1c62374-1b67-42eb-9afe-9bcf1569dfd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>35ab7d74-2220-40d4-ba2c-7009d6502a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnNext' and @name = 'btnNext' and (text() = 'Avanti' or . = 'Avanti')]</value>
      <webElementGuid>9d83d022-0d80-458f-ae84-1e633c84a6ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
