<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>agreePPjp</name>
   <tag></tag>
   <elementGuidId>f3f3a987-249b-4867-befc-e86c82194c67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[1]/div[4]/div[1]/div[13]/div[2]/form/fieldset/div[2]/ul/div[3]/div[2]/div/div[1]/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
