<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectPPjp</name>
   <tag></tag>
   <elementGuidId>0e20f2a7-0e2f-476b-9ea2-afdaabf46b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[1]/div[4]/div[1]/div[13]/div[2]/form/fieldset/div[2]/ul/div[3]/div[1]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
