<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCIconCH</name>
   <tag></tag>
   <elementGuidId>d13b4255-ee25-43e8-a671-c31227bbbe21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/footer/div[1]/div/div/div/div[5]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/footer/div[1]/div/div/div/div[5]/a/img</value>
      <webElementGuid>799cde61-e9b6-4a93-969a-de8c0118a9c8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
