<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>agreetoterms</name>
   <tag></tag>
   <elementGuidId>dc438f7d-2ea1-42dd-a97c-6c23616165e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[1]/div[4]/div[1]/div[14]/div[2]/form/fieldset/div[2]/ul/div[4]/div[2]/div/div[1]/div/label/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
