<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>INT - Log In Out</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4614c81f-8583-4509-8517-4d87feff8062</testSuiteGuid>
   <testCaseLink>
      <guid>a6085b25-ed9e-4c0e-afe9-3cfb7f10c1e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/AT - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22dcaff0-802f-4813-acc8-bfc934765562</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f37b4498-b246-445c-bf55-e6fa93ea9960</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/CH - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eac1439e-ad73-4f64-b850-cddfefdfc31d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08b8bdea-d689-4e4d-b858-c0131d110661</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/CZ - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>886e655f-d5f7-48a5-a92b-60d1cf73fc72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cad3a172-9c09-48b2-8786-e4f816b642f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/DE - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f97c7614-9f41-4d4c-a7a3-2d8ee74a92f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a76cccc-46d0-4564-8ad6-0b78e6e8c116</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/ES - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e874f61-41c9-4ed8-8903-e97dad63dd25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b465f5d-146e-4d4d-b3f0-41bbe36da7ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/FR - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0769b24f-0a3f-452a-9d99-5ae1e1014602</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b628500f-c0be-4c70-8d75-1350fa0104ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/PL - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e24a8d54-8e53-4083-8068-0d9b2c7253d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6a84dbc-131b-453c-8a3f-c75448f9bce3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/PT - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>233518f0-5a66-41ba-8af6-af5ae1257572</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4361ada8-9057-42dd-babb-90fbf17ee769</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/UK - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b41c55-d367-45d0-9627-8e8ab78625e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c2cb57e-0d98-4166-a2b5-ddb8413e714d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/INT/Log in and out/US - Log In Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6fcb95b-235f-4139-998b-99ac93f268b4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
