<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payPPus</name>
   <tag></tag>
   <elementGuidId>5181f48f-eb68-4271-9b8f-b4ec27d1e1f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[1]/div[4]/div[1]/div[13]/div[2]/form/fieldset/div[2]/ul/div[3]/div[2]/div/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
