<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectBlik</name>
   <tag></tag>
   <elementGuidId>95670778-b2e3-41c9-b652-3599777ccbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[1]/div[2]/div/div[1]/div[12]/div[2]/form/fieldset/div[2]/ul/div[4]/div[1]/label/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
