<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sellSoulPPIt</name>
   <tag></tag>
   <elementGuidId>337ee19f-f5dd-4e53-bc49-7bb61fe079d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[3]/div[1]/div[12]/div[2]/form/fieldset/div[2]/ul/div[3]/div[2]/div/div[1]/div/div[1]/label/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[3]/div[1]/div[12]/div[2]/form/fieldset/div[2]/ul/div[3]/div[2]/div/div[1]/div/div[1]/label/span[1]</value>
      <webElementGuid>f2c7eadb-c9d5-42c3-8b45-c723d6c3b1ec</webElementGuid>
   </webElementProperties>
</WebElementEntity>
