<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_dwfrm_profile_customer_email</name>
   <tag></tag>
   <elementGuidId>2b5d848c-51f0-431a-ba62-4dde63e95f51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration-form-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55b9055b-00b5-475d-92c8-464918965f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*E-mail</value>
      <webElementGuid>47678197-deaa-4f48-9d0c-56f7df9ee96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>*E-mail</value>
      <webElementGuid>48d1d95d-32ba-45ae-9919-0019a4797348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba63af85-37e0-42f7-be45-e2f7594233c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-email</value>
      <webElementGuid>929614e7-adb7-4636-a23c-dc758262392a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>14b9319f-38df-4384-b050-9051a9101db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Inserisci una e-mail valida.</value>
      <webElementGuid>929f9f74-7864-4933-a50e-029f6776d47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-type-message</name>
      <type>Main</type>
      <value>Inserisci una e-mail valida.</value>
      <webElementGuid>86a8f772-951c-4e8b-9954-1dde2c8945ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profile_customer_email</value>
      <webElementGuid>4eab9a75-d63c-4774-9445-c8e31e60e2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e42407d4-13cc-4e53-bade-43543a06accc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>56667e97-4ab5-4b7f-ad23-39927aa04930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\w.%+-]+@[\w.-]+\.[\w]{2,6}$</value>
      <webElementGuid>63557376-06e6-4a80-bc50-83cca4733d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-valid-input</value>
      <webElementGuid>f809d8f5-99b6-457c-8561-03db493b262f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-email&quot;)</value>
      <webElementGuid>2f3646a3-5eeb-4e4d-b541-7675953ca1e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-email']</value>
      <webElementGuid>04587595-be91-4705-81cb-efebcc6933e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-registration-cell']/div/form/label/input</value>
      <webElementGuid>a814461c-7196-4edb-b7db-a378a99f2aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/label/input</value>
      <webElementGuid>68a182d3-1036-4e63-a8d7-a172b1578e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '*E-mail' and @title = '*E-mail' and @type = 'text' and @id = 'registration-form-email' and @name = 'dwfrm_profile_customer_email']</value>
      <webElementGuid>d8ccf3e8-56ba-4638-8e37-f0c38c631f87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
