<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basket</name>
   <tag></tag>
   <elementGuidId>32396ab4-e6ae-478d-b83c-dcf9ecdf4d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/header/nav/div/div[1]/div[3]/div/div[2]/div[4]/div[1]/a/svg/use</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
