<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ovdjeidemailCLZuk</name>
   <tag></tag>
   <elementGuidId>2df44c2a-7219-4d7e-b797-a6e6798bf63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newsletter-Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newsletter-Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bd49eaf-e1c5-4a8f-af5f-0962453a0e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newsletter-Email</value>
      <webElementGuid>b593478b-6515-4aea-b201-4f391dada301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>386d3804-c434-446e-a3a7-658532f73e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>f8e5d1d5-c8d7-45bf-8f47-6acd06bf537e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-field input-newsletter clear has-round-icon</value>
      <webElementGuid>7f0699d4-8455-4250-9db8-13f275ea08d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>5769c8dd-58a4-4258-9c89-d98620c9de39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2171b0d6-5d11-4eb8-81d0-231501b3b3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>99599072-6fc3-427f-9018-5b48a8416e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-error-message</name>
      <type>Main</type>
      <value>*Please enter a valid email address</value>
      <webElementGuid>119e072c-1b4c-427b-ad9e-281a6e0ecc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>*label.input.email</value>
      <webElementGuid>75665a28-94dc-49cd-bf7e-41e89a7808ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>#email-errors</value>
      <webElementGuid>76e118ca-9f3e-4e33-a1c7-a78bcd9461f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newsletter-Email&quot;)</value>
      <webElementGuid>1efac3f8-d47d-4dde-88fb-0121c2f7a42b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newsletter-Email']</value>
      <webElementGuid>75a93435-c342-4ccd-9e26-3cfe1b53f4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newsletterFooterForm']/div/label/input</value>
      <webElementGuid>e9e216d5-a9f8-49e8-a27e-899f0ad574a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/input</value>
      <webElementGuid>e7420ea8-fdea-42f5-9149-b90bba4ceed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'newsletter-Email' and @name = 'email' and @title = 'Email' and @placeholder = 'Email' and @type = 'text']</value>
      <webElementGuid>bb926e3f-0378-4024-b528-553f69641943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
