<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>523d6366-efe7-4a36-bdca-046a6b2c864a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.arrow.arrow-action-close > img[alt=&quot;open&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainpdpform']/div[2]/div/div/a/div/i[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a5877580-699a-4c16-b3a1-d39ba9a7e6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>0c02ba70-5eb1-42b3-9f00-b940fc40d138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/on/demandware.static/Sites-calzedonia-de-Site/-/default/dwf7da0b8e/images/arrow-bottom.png</value>
      <webElementGuid>067d4541-9413-4ebf-8d05-7d8bf0439abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>cea26432-eb3a-4382-8f27-41a0342ecc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionSidebar&quot;)/div[@class=&quot;cell large-10&quot;]/div[@class=&quot;grid-x grid-margin-x js-pickable-content-desktop-container hide-for-small-only&quot;]/div[@class=&quot;cell small-10&quot;]/span[@class=&quot;grid-x&quot;]/div[@class=&quot;cell large-10&quot;]/div[@class=&quot;attribute-container&quot;]/div[@class=&quot;attribute&quot;]/div[@id=&quot;mainpdpform&quot;]/div[@class=&quot;hide-for-small-only&quot;]/div[@class=&quot;attribute&quot;]/div[@class=&quot;action-bar grid-x drop-down-size-selector&quot;]/a[@class=&quot;cell small-3 size-dropdown-data-wrapper js-panel-opener data-a&quot;]/div[@class=&quot;data-container&quot;]/i[@class=&quot;arrow arrow-action-close&quot;]/img[1]</value>
      <webElementGuid>17892256-12e5-4faf-bf84-b37094dc2c36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainpdpform']/div[2]/div/div/a/div/i[2]/img</value>
      <webElementGuid>59a47025-ff86-4b77-aae8-06d58a575edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='open'])[2]</value>
      <webElementGuid>4d39b04a-55b1-4619-a08b-ed213bbc5651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]/img</value>
      <webElementGuid>7e78dac2-84eb-4f3f-9083-04762970a433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/on/demandware.static/Sites-calzedonia-de-Site/-/default/dwf7da0b8e/images/arrow-bottom.png' and @alt = 'open']</value>
      <webElementGuid>9724d4b8-2429-4a71-a924-135090c3374f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
