<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S_emailNotify</name>
   <tag></tag>
   <elementGuidId>9568aecc-7a7a-4286-8ea6-0952df76e2dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailNotify</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailNotify']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1afc15bc-fde6-4214-a7ec-46976d61d04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b06e7ce3-671e-4b48-9327-f999d1cd82ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailNotify</value>
      <webElementGuid>76896509-70fd-4a83-8e0e-28bd92edd270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>marginTop</value>
      <webElementGuid>51a0016f-5e77-44e2-a35c-076d205ca481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\w.%+-]+@[\w.-]+\.[\w]{2,6}$</value>
      <webElementGuid>6851c6ce-c0e1-4597-a35a-f5a92340752f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailNotify</value>
      <webElementGuid>66232c10-1f3c-4b50-a632-2bccbcd3fdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E-Mail-Adresse eingeben</value>
      <webElementGuid>3d1f6476-496b-4339-ad3f-b78a5642aeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailNotify&quot;)</value>
      <webElementGuid>de52aefd-0d15-4d2f-a925-2e0f5c80597d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailNotify']</value>
      <webElementGuid>e0d2c08d-a5bc-4bdc-af33-f19e3f20a6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div/div/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>acc69dee-abc5-4903-bf65-83af0ace1149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8fe2123c-fec9-4222-9d97-e9544f42ebc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailNotify' and @name = 'emailNotify' and @placeholder = 'E-Mail-Adresse eingeben']</value>
      <webElementGuid>6eb19268-7add-4771-affd-d8d8b6adcbbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
