<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>331905d6-7f0e-46c9-a660-a65882640bb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.geoblock-close-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='geoblock-close']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14d2c080-174c-4b9b-bfdd-56b5a937e55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>geoblock-close-text</value>
      <webElementGuid>2d327f25-3dc3-4676-9e96-b2d0d3cd59db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Esci</value>
      <webElementGuid>13e4c1d1-310f-4486-822b-85bc82fb7432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>96e18a67-6b52-4d00-b34e-20937e8584df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geoblock-close&quot;)/span[@class=&quot;geoblock-close-text&quot;]</value>
      <webElementGuid>0a370588-d29e-4fbb-94d4-29e0e5ab6e51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='geoblock-close']/span</value>
      <webElementGuid>882f0ffb-d1a3-407b-a58b-ea084b9f0bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Besuche den E-Shop deines Landes:'])[1]/following::span[2]</value>
      <webElementGuid>1298fd2e-b346-4c43-9c6f-dff606fcb465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'geoblock-close', '&quot;', ')/span[@class=', '&quot;', 'geoblock-close-text', '&quot;', ']')])[1]/preceding::span[1]</value>
      <webElementGuid>c2a2353f-9c13-4f47-ad99-64f7da0a84ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sie haben noch keine Antwort auf Ihre Frage gefunden?'])[1]/preceding::span[1]</value>
      <webElementGuid>ebaeb84d-b708-44f1-86db-56c96fbb9fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div[2]/button/span</value>
      <webElementGuid>cb46cb1d-341b-42f6-8281-f8212e6815a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>18c1f55f-5f88-4952-92aa-258490b42b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
