<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Previous_tile-image slick-slide slick-c_6cfe23</name>
   <tag></tag>
   <elementGuidId>52422eb1-ea95-4af8-b814-450a5e749547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search-results']/div/div[2]/div/div[2]/section/div/div/a/div/section/div/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.tile-image.slick-slide.slick-current.slick-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>105f6312-0d83-4753-ac5d-df6858c43017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-image slick-slide slick-current slick-active</value>
      <webElementGuid>7d53782c-045b-46e0-931d-48d29e95ccef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a9eb9c8e-f29b-40ed-97bd-bb826e3a9f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test.calzedonia.com/dw/image/v2/BJHW_DEV/on/demandware.static/-/Sites-CAL_EC_COM/default/dw468b19f8/images/LIC030_wear_019_F.jpg?sw=400&amp;sfrm=png</value>
      <webElementGuid>06c33550-4aa5-4b08-be25-6419dfc63cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Collant Shaping Velatissimi 8 Denari con Control Top</value>
      <webElementGuid>e35e0072-957c-4e44-852f-314a28e40da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Collant Shaping Velatissimi 8 Denari con Control Top</value>
      <webElementGuid>996aa4bf-b8c6-47b7-a9d3-e8dc3e556604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://test.calzedonia.com/dw/image/v2/BJHW_DEV/on/demandware.static/-/Sites-CAL_EC_COM/default/dw468b19f8/images/LIC030_wear_019_F.jpg?sw=400&amp;sfrm=png 400w,https://test.calzedonia.com/dw/image/v2/BJHW_DEV/on/demandware.static/-/Sites-CAL_EC_COM/default/dw468b19f8/images/LIC030_wear_019_F.jpg?sw=600&amp;sfrm=png 600w,https://test.calzedonia.com/dw/image/v2/BJHW_DEV/on/demandware.static/-/Sites-CAL_EC_COM/default/dw468b19f8/images/LIC030_wear_019_F.jpg?sw=800&amp;sfrm=png 800w,https://test.calzedonia.com/dw/image/v2/BJHW_DEV/on/demandware.static/-/Sites-CAL_EC_COM/default/dw468b19f8/images/LIC030_wear_019_F.jpg?sw=1200&amp;sfrm=png 1200w</value>
      <webElementGuid>6d139e57-665c-455f-a4e8-9a3c81a93a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width:1023px) 70vw, 33vw</value>
      <webElementGuid>1f7dc282-a14e-4b8d-b4e9-a1f5691d3900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>37dc4154-b1cf-4c98-891e-4b120f92d1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1700</value>
      <webElementGuid>ac9b03ce-1636-4f4e-af99-f7058a96ddd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2550</value>
      <webElementGuid>c5fbf9c4-b33f-4715-8874-357b9995fa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slick-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4307213a-5855-4f73-a8ca-43fbc292cc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05f92e74-b961-4cb4-8abd-06484db216ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f67e1ca1-bcdf-4ebe-aff6-b6c4b7a747fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;grid-x grid-container-full js-plpPageContainer&quot;]/div[@class=&quot;cell&quot;]/section[@class=&quot;grid-x productsContainer&quot;]/div[@class=&quot;cell productItem productItem-plpOnly productItem-normal&quot;]/div[@class=&quot;product&quot;]/a[@class=&quot;product-tile js-pdp-link no-hover&quot;]/div[@class=&quot;image-container&quot;]/section[@class=&quot;js-tileImageCarousel slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/img[@class=&quot;tile-image slick-slide slick-current slick-active&quot;]</value>
      <webElementGuid>7f50e90c-bf57-40bd-96e9-2674ab29b9e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div/div[2]/div/div[2]/section/div/div/a/div/section/div/div/img[2]</value>
      <webElementGuid>b342f3ff-d813-4fc1-938a-a91bc6e57f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Collant Shaping Velatissimi 8 Denari con Control Top'])[2]</value>
      <webElementGuid>6a974898-a526-44d6-8040-d2a32729c5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>c918d117-880c-42ea-8cfa-dd74ae3716dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://test.calzedonia.com/dw/image/v2/BJHW_DEV/on/demandware.static/-/Sites-CAL_EC_COM/default/dw468b19f8/images/LIC030_wear_019_F.jpg?sw=400&amp;sfrm=png' and @alt = 'Collant Shaping Velatissimi 8 Denari con Control Top' and @title = 'Collant Shaping Velatissimi 8 Denari con Control Top']</value>
      <webElementGuid>32ac1095-4980-4d93-8558-121eca3c2bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
