<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ANMELDEN  REGISTRIEREN_q</name>
   <tag></tag>
   <elementGuidId>f23a08f0-2d3b-4d2c-bdbc-1230eaac90ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;q&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85a3d059-ac02-4d2a-ab90-dc4bb80badab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-field</value>
      <webElementGuid>2b633f7e-4e90-4fdd-902a-a7f1a9b31a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7d45494d-0895-490c-8d1c-c478378b5b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>006d039a-df1b-41ec-bfeb-bd10d145a12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Suchen</value>
      <webElementGuid>28bcde57-e232-4bcc-9e2f-7e1d036f3bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Suchen</value>
      <webElementGuid>bb74138e-aef9-43bd-bf42-c14e9efc145a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>22792ebe-2aa6-4073-8c66-fdfc00dc4f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Suchen</value>
      <webElementGuid>6ebda1da-81ae-4555-92be-8f8129fea830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;fpls-js ls-tab-off&quot;]/div[@class=&quot;page page-home-gender&quot;]/header[@class=&quot;main-header pos-relative&quot;]/nav[@class=&quot;solid&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;top-row grid-x&quot;]/div[@class=&quot;cell medium-shrink small-2 first-for-medium-down grid-x&quot;]/span[@class=&quot;main-header-search header-search hide-for-small-only&quot;]/div[@class=&quot;site-search mobile-search&quot;]/form[@class=&quot;pos-relative&quot;]/input[@class=&quot;form-control search-field&quot;]</value>
      <webElementGuid>a9f56015-d99f-4640-be94-6eb0b282874d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='q']</value>
      <webElementGuid>85464296-0d66-45a2-99bc-fae3315e863f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[4]/header/nav/div/div/div[4]/span/div/form/input</value>
      <webElementGuid>54df5833-ab12-4d9f-bba9-8d4fb0997f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>40b87d74-15b5-4ca3-b8e1-590a32d2a387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 'q' and @title = 'Suchen' and @placeholder = 'Suchen']</value>
      <webElementGuid>9fb31022-dd0f-487c-8fcf-9b0b9c02f5f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
