<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Gib in jedem Feld eine gltige Anzahl e_aa200c</name>
   <tag></tag>
   <elementGuidId>829004e7-bc2a-45be-85fd-79e9ee565ba1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div[6]/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2027944-cc10-4b90-93af-8b94466f5cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input</value>
      <webElementGuid>759958cd-596a-4403-93d3-c473f49d8701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;fpls-js ls-tab-off tingle-enabled&quot;]/div[@class=&quot;tingle-modal newsletter-popup tingle-modal--visible&quot;]/div[@class=&quot;tingle-modal-box&quot;]/div[@class=&quot;tingle-modal-box__content&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell medium-5&quot;]/div[@class=&quot;newsletter-popup__content&quot;]/form[@class=&quot;registerNewsletter&quot;]/div[1]/div[@class=&quot;cell mobilePadding grid-x&quot;]/div[@class=&quot;cell medium-4 input-error-group error-outside checkboxMarginMobileDesktop&quot;]/label[@class=&quot;boolean-field&quot;]/span[@class=&quot;checkbox-input&quot;]</value>
      <webElementGuid>912b72ac-2d64-4bf0-b3ae-1b6a14b8f513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div[6]/div[2]/label/span</value>
      <webElementGuid>8b613e3d-fbef-478b-b7a8-ebbcc687e41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span</value>
      <webElementGuid>592e4fe6-ee24-4bcf-ac0f-a12e29843c3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
