<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bitte whle eine Anrede aus_radio-input</name>
   <tag></tag>
   <elementGuidId>bd3dff95-0452-40c6-9261-a338d5d4ccb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.radio-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div/div[3]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a4ef183-54cd-43e3-bf11-0360e0fb1c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-input</value>
      <webElementGuid>b4b32ff2-3175-4bf1-a490-0de5c0d40844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;fpls-js ls-tab-off tingle-enabled&quot;]/div[@class=&quot;tingle-modal newsletter-popup tingle-modal--visible&quot;]/div[@class=&quot;tingle-modal-box&quot;]/div[@class=&quot;tingle-modal-box__content&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell medium-5&quot;]/div[@class=&quot;newsletter-popup__content&quot;]/form[@class=&quot;registerNewsletter&quot;]/div[1]/div[@class=&quot;cell&quot;]/div[@class=&quot;cell medium-6 mrmrsChoice&quot;]/div[1]/label[@class=&quot;boolean-field mobilePadding&quot;]/span[@class=&quot;radio-input&quot;]</value>
      <webElementGuid>3fc98e9c-ba54-4b11-8472-4726ff37b658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div/div[3]/div/label/span</value>
      <webElementGuid>f1ecb1ca-b178-4ebc-88e8-3bfd5f6df91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>eb7637f2-c97d-464c-b2d7-2f565b74a3db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
