<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ja_checkbox-input</name>
   <tag></tag>
   <elementGuidId>96bb16f3-04fc-4362-a791-7ab8f1c4d758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div[7]/div[2]/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66f7d06d-07b8-4070-9ba3-f21b33e00871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input</value>
      <webElementGuid>bc44ab70-e5da-4d9e-9e82-0ac80317220b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;fpls-js ls-tab-off tingle-enabled&quot;]/div[@class=&quot;tingle-modal newsletter-popup tingle-modal--visible&quot;]/div[@class=&quot;tingle-modal-box&quot;]/div[@class=&quot;tingle-modal-box__content&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell medium-5&quot;]/div[@class=&quot;newsletter-popup__content&quot;]/form[@class=&quot;registerNewsletter&quot;]/div[1]/div[@class=&quot;cell mobilePadding grid-x&quot;]/div[@class=&quot;cell medium-4 input-error-group error-outside lockable checkboxMarginMobileDesktopTargeted&quot;]/label[@class=&quot;boolean-field&quot;]/span[@class=&quot;checkbox-input&quot;]</value>
      <webElementGuid>dd0d5dc3-69aa-427c-9b14-4e77eab43255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div[7]/div[2]/label[2]/span</value>
      <webElementGuid>fda829f7-ef3f-4503-a394-ae807426c23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/label[2]/span</value>
      <webElementGuid>8ce807ab-e0cd-4175-a664-d480b23399dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
