<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept Recommended Cookies  Continue</name>
   <tag></tag>
   <elementGuidId>6b3d8ab0-4e58-4a65-a1b4-97595ba77924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f28f8ecd-5367-45f6-aec8-881165698860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept</value>
      <webElementGuid>a94ec2f0-6f94-467f-9db9-acb262771b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>accept()</value>
      <webElementGuid>060e8d4c-9bc8-44ec-9fa7-86ede277fc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept Recommended Cookies &amp; Continue</value>
      <webElementGuid>60a29016-d652-4adc-b194-f0decdd4ba2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept&quot;)</value>
      <webElementGuid>5dc2c914-0edf-428a-babf-80670e538c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='accept']</value>
      <webElementGuid>a6d30a52-d29c-4330-99ab-7cee19c8b509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cons-btns']/button[4]</value>
      <webElementGuid>5924df7c-f385-4d75-8e4f-8455baf042b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow Necessary Cookies &amp; Continue'])[1]/following::button[1]</value>
      <webElementGuid>549d0740-b2ed-41ee-8886-d901214c341d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure cookies'])[1]/following::button[3]</value>
      <webElementGuid>b7f2d7f4-9ed4-4262-9754-9b48720a7fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[2]/preceding::button[1]</value>
      <webElementGuid>466581f6-7326-41d5-93e5-7f7f8057a524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'accept', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>27242fba-32ce-4d36-b176-cd505b28d019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept Recommended Cookies &amp; Continue']/parent::*</value>
      <webElementGuid>fa0958e7-69e5-4f26-89e7-b433350a8e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>7c4bdb0a-cfe5-40d0-874a-c615b81879b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'accept' and (text() = 'Accept Recommended Cookies &amp; Continue' or . = 'Accept Recommended Cookies &amp; Continue')]</value>
      <webElementGuid>95df9f34-8b69-4e2a-9f79-328a3af4f026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
