<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_V ao seu carrinho de compras</name>
   <tag></tag>
   <elementGuidId>edcba125-716a-4363-937b-c274208dc778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='checkout-button-secure-checkout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkout-button-secure-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd3b5417-382b-4be6-a9a1-b32f0c3d7523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-button-secure-checkout</value>
      <webElementGuid>6ae5d907-95e5-43f8-aaf3-edf6728cb9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://test.intimissimi.com/pt/cart/</value>
      <webElementGuid>80e2eb70-87bb-4366-afd9-192ba2219e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button extended uppercase minicart-checkout-button</value>
      <webElementGuid>fcf0e444-d337-4059-b17c-db3458ff06ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1eb6ab08-1990-4ba1-8521-e82479474239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d6800578-cd02-4c0c-9831-3d5ae1267b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Vá ao seu carrinho de compras
</value>
      <webElementGuid>b1b2d5d6-65f1-40f7-a702-8534a110f6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;fpls-js ls-tab-off&quot;]/div[@class=&quot;page&quot;]/header[@class=&quot;main-header&quot;]/nav[@class=&quot;solid&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-x menu-top-grid&quot;]/div[@class=&quot;main-header-wrap secondary-menu-wrap cell small-3 grid-x&quot;]/div[@class=&quot;ico-header-menu&quot;]/div[@class=&quot;main-header-login first-level&quot;]/div[@class=&quot;minicart open&quot;]/div[@class=&quot;popover popover-bottom show&quot;]/div[@class=&quot;container cart analytics-mini-cart promoapplied&quot;]/div[@class=&quot;grid-x button-grid-minicart&quot;]/div[@class=&quot;small-10 checkout-continue text-center&quot;]/div[@class=&quot;checkoutButtons grid-x&quot;]/a[@id=&quot;checkout-button-secure-checkout&quot;]</value>
      <webElementGuid>ebe1bc0d-848f-4bf6-a7ed-a0040928f59a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='checkout-button-secure-checkout']</value>
      <webElementGuid>aa15a965-21bd-47cc-adc5-305a649db0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[3]/header/nav/div/div/div[3]/div/div[2]/div[4]/div[2]/div/div[4]/div/div/a</value>
      <webElementGuid>00ad5cc0-5a97-4ab5-a14d-be2b166f7a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vá ao seu carrinho de compras')]</value>
      <webElementGuid>90ad8388-45ad-402a-bb7c-7f27d3a8e220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parabéns! Completou a promoção test promo'])[1]/following::a[1]</value>
      <webElementGuid>5c58ffe4-1982-4e1a-8e45-9f85f90da022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test promo'])[1]/preceding::a[1]</value>
      <webElementGuid>23ca15d5-20e7-41c2-b228-0c9ffe310e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vá ao seu carrinho de compras']/parent::*</value>
      <webElementGuid>a51ed472-dff9-42e8-9d2a-37ca4acc3b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://test.intimissimi.com/pt/cart/')])[2]</value>
      <webElementGuid>ac0cd39b-ff1d-4256-9f3c-0200e7027314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/a</value>
      <webElementGuid>0788da3f-8082-4dec-97eb-668260b39fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'checkout-button-secure-checkout' and @href = 'https://test.intimissimi.com/pt/cart/' and (text() = '
Vá ao seu carrinho de compras
' or . = '
Vá ao seu carrinho de compras
')]</value>
      <webElementGuid>83fa0ce1-ba36-4a57-9061-48c1a4e1c2ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
