<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plusOneCart</name>
   <tag></tag>
   <elementGuidId>cf83e1d0-a9c9-4dfc-a9d9-88d1802dc043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div[3]/div[3]/div/div/section/div[1]/div/div[2]/div[5]/div[1]/span/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
