<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PayPal_checkbox-input</name>
   <tag></tag>
   <elementGuidId>c08d1613-1b8d-4fb2-b470-c5ac41bd09c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paypal-content']/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paypal-content > div.policy-promotion-payment.policy-terms-block > div.form-group.error-inside > label.boolean-field > span.checkbox-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypal-content&quot;)/div[@class=&quot;policy-promotion-payment policy-terms-block&quot;]/div[@class=&quot;form-group error-inside&quot;]/label[@class=&quot;boolean-field&quot;]/span[@class=&quot;checkbox-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paypal-content']/div/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
