<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fd35119b-9e3c-4d2c-b46c-56b1175a6451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainpdpform']/div[2]/div/div/a/div/i[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.arrow.arrow-action-close > img[alt=&quot;open&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9e30d1fb-919e-478c-aacc-3cdb8b51b6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>12c3b980-b3cd-447d-bcda-cb6da22e9b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/on/demandware.static/Sites-calzedonia-eu-Site/-/default/dwf1e3fb58/images/arrow-bottom.png</value>
      <webElementGuid>9651ca57-b4f1-4db2-9ead-0f3281273f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>73d333cd-6f2f-4b2b-9838-dc8b99130bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionSidebar&quot;)/div[@class=&quot;cell large-10&quot;]/div[@class=&quot;grid-x grid-margin-x js-pickable-content-desktop-container hide-for-small-only&quot;]/div[@class=&quot;cell small-10&quot;]/span[@class=&quot;grid-x&quot;]/div[@class=&quot;cell large-10&quot;]/div[@class=&quot;attribute-container&quot;]/div[@class=&quot;attribute&quot;]/div[@id=&quot;mainpdpform&quot;]/div[@class=&quot;hide-for-small-only&quot;]/div[@class=&quot;attribute&quot;]/div[@class=&quot;action-bar grid-x drop-down-size-selector&quot;]/a[@class=&quot;cell small-3 size-dropdown-data-wrapper js-panel-opener data-a&quot;]/div[@class=&quot;data-container&quot;]/i[@class=&quot;arrow arrow-action-close&quot;]/img[1]</value>
      <webElementGuid>23de3ad0-b82f-4b16-b140-fb46db7e6c59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainpdpform']/div[2]/div/div/a/div/i[2]/img</value>
      <webElementGuid>e57b6c56-3d7d-44a1-bad9-32716ebf8aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='open'])[2]</value>
      <webElementGuid>891eb2a6-19a1-4d5e-aeda-f892f3e574a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]/img</value>
      <webElementGuid>ff6ca753-ee9b-43e9-9fe0-23cedb38c332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/on/demandware.static/Sites-calzedonia-eu-Site/-/default/dwf1e3fb58/images/arrow-bottom.png' and @alt = 'open']</value>
      <webElementGuid>c6e00e66-17e4-49cf-8f38-fc07bc7592aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
