<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>ce770632-bed0-4947-9003-4418c53ec11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chooseBonusProductModal']/div[2]/div/div/div/div[3]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.free-gift-green-close-button.close-custom.js-close-button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fdd5e67c-9f0e-4992-b4d8-1241141e7d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24f6794d-4bae-43b7-89de-1f319f9fd252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>4e4bc171-834b-42a8-9375-21621c03e6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseBonusProductModal&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;bonus-product-item ready-to-order choice-of-bonus-product&quot;]/div[@class=&quot;product-quickview product-freegift product-master col product-wrapper product-detail&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell large-auto pos-relative&quot;]/div[@class=&quot;banner-free-gift-green&quot;]/button[@class=&quot;free-gift-green-close-button close-custom js-close-button&quot;]/span[1]</value>
      <webElementGuid>4fc4e895-069f-4722-9f9e-d14e4275a3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chooseBonusProductModal']/div[2]/div/div/div/div[3]/div/button/span</value>
      <webElementGuid>63426e18-f6cf-4f8d-932d-3a42a1e3e564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Bonus Products'])[1]/following::span[1]</value>
      <webElementGuid>83d965ac-4a00-4618-966d-91840d27958d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calzini corti classici'])[1]/preceding::span[1]</value>
      <webElementGuid>637992de-e05c-4ddc-aefa-d7a7ab1fe9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MODZ0233'])[1]/preceding::span[1]</value>
      <webElementGuid>68514a47-93c7-4a37-95b5-83a2e1263b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span</value>
      <webElementGuid>45394444-10bb-437d-a24c-dc237faaab67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>79187ded-c4a9-4d6a-88c3-e1b82fbb1206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
