<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>a779dd42-9cd7-455f-9378-1cf887086c91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//use[@href = '/on/demandware.static/Sites-calzedonia-eu-Site/-/it_IT/v1654003812778/images/sprite.svg#più']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>ee42102c-b971-414f-827e-f6e1018ab3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/on/demandware.static/Sites-calzedonia-eu-Site/-/it_IT/v1654003812778/images/sprite.svg#più</value>
      <webElementGuid>039b6435-ba91-42f0-b120-ca3c54446f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionSidebar&quot;)/div[@class=&quot;cell large-10&quot;]/div[@class=&quot;grid-x grid-margin-x js-pickable-content-desktop-container hide-for-small-only&quot;]/div[@class=&quot;cell small-10&quot;]/span[@class=&quot;grid-x&quot;]/div[@class=&quot;cell large-7 attribute-container container-flex-desktop-quantity-message quantity hide-for-small-only&quot;]/div[@class=&quot;size-selectore&quot;]/span[@class=&quot;quantityButtons&quot;]/button[@class=&quot;quantity-button no-margin&quot;]/i[@class=&quot;icon&quot;]/svg[@class=&quot;small&quot;]/use[1]</value>
      <webElementGuid>5aa590a3-8edc-456f-bad3-5f1ca14904ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//use[@href = '/on/demandware.static/Sites-calzedonia-eu-Site/-/it_IT/v1654003812778/images/sprite.svg#più']</value>
      <webElementGuid>4c9d7be5-9200-4ff4-9fe1-8af85e51b624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
