<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nein_checkbox-input</name>
   <tag></tag>
   <elementGuidId>ed3ea75c-da8a-40b8-9d68-9939a26f387b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cell.medium-4.input-error-group.error-outside.lockable.checkboxMarginMobileDesktopTargeted > label.boolean-field > span.checkbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div[7]/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;ls-tab-off tingle-enabled&quot;]/div[@class=&quot;tingle-modal newsletter-popup tingle-modal--visible&quot;]/div[@class=&quot;tingle-modal-box&quot;]/div[@class=&quot;tingle-modal-box__content&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell medium-5&quot;]/div[@class=&quot;newsletter-popup__content&quot;]/form[@class=&quot;registerNewsletter&quot;]/div[1]/div[@class=&quot;cell mobilePadding grid-x&quot;]/div[@class=&quot;cell medium-4 input-error-group error-outside lockable checkboxMarginMobileDesktopTargeted&quot;]/label[@class=&quot;boolean-field&quot;]/span[@class=&quot;checkbox-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/form/div/div[7]/div[2]/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/label/span</value>
   </webElementXpaths>
</WebElementEntity>
