<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Esci</name>
   <tag></tag>
   <elementGuidId>e23c308a-7805-478f-8890-6e6da35d718c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.subtitle-two</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div[2]/div[5]/div/div/div/div/div/a/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>195d790d-ddfd-4157-870a-26ad5b112f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subtitle-two</value>
      <webElementGuid>6121d818-faf1-4a12-842c-c7f69dfde3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esci</value>
      <webElementGuid>68e7285a-4f3d-4499-ab89-ca5e7a993113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;ls-tab-off&quot;]/div[@class=&quot;page page--full page--login&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-x align-center&quot;]/div[@class=&quot;cell small-10 grid-x grid-margin-x&quot;]/div[@class=&quot;cell small-10 hide-for-small-only&quot;]/div[@class=&quot;account-header&quot;]/div[@class=&quot;title-container&quot;]/a[@class=&quot;right&quot;]/h3[@class=&quot;subtitle-two&quot;]</value>
      <webElementGuid>3a7bb966-a6fd-4bda-8cd8-54cd9ef3cbf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[2]/div[5]/div/div/div/div/div/a/h3</value>
      <webElementGuid>7f06f2d9-80f5-458b-b12a-b0a07860d3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciao imeIdeOvdje'])[1]/following::h3[1]</value>
      <webElementGuid>356dbc51-7473-4691-af76-61e08fff5695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scopri il programma'])[1]/following::h3[1]</value>
      <webElementGuid>28274c0f-08ed-44a3-a37e-5e1cb202903d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciao imeIdeOvdje'])[2]/preceding::h3[1]</value>
      <webElementGuid>01e91063-34dd-4bc2-bbb5-bc2bba581e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esci'])[3]/preceding::h3[1]</value>
      <webElementGuid>befc2170-1477-41db-bd95-515b767acd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>c2ac9a8a-edbc-4345-b2bc-7232430d5aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Esci' or . = 'Esci')]</value>
      <webElementGuid>342c48b4-ddae-4ecf-adb4-d398b76eef5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
