<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Donna_prehome-img hide-for-small-only</name>
   <tag></tag>
   <elementGuidId>2a682ce0-1304-476a-8e87-fb313b270929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.prehome-img.hide-for-small-only</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='catWoman']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4faea3cc-8e04-447b-9370-6c9d69b40094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prehome-img hide-for-small-only</value>
      <webElementGuid>8e3b1b3c-4e67-4da8-ba5a-3a7b21e5736f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg</value>
      <webElementGuid>a3913b78-73e8-4936-b01b-b9b788a935b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catWoman&quot;)/a[1]/img[@class=&quot;prehome-img hide-for-small-only&quot;]</value>
      <webElementGuid>de3f1f43-6152-43e7-a1f2-00d639977837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5e247285-5d84-4868-a07a-9db6c58cf04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prehome-img hide-for-small-only</value>
      <webElementGuid>a88016db-c7c0-407e-b2e8-b2f30303c7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg</value>
      <webElementGuid>83c97803-2bff-454e-9e69-220977985cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catWoman&quot;)/a[1]/img[@class=&quot;prehome-img hide-for-small-only&quot;]</value>
      <webElementGuid>b8c3d47e-6048-4d58-b9ca-fbdd9624eaef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catWoman']/a/img</value>
      <webElementGuid>3a82d1b6-0647-43c8-843e-dee71b5df332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg')]</value>
      <webElementGuid>9d827db5-c2ea-4dc9-a575-9e47d9b42ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1aa12507-ce10-4668-85a0-637b85738606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://test.calzedonia.com/on/demandware.static/-/Library-Sites-CalzedoniaContentLibrary/default/dw89839cb6/images/hp/CLZ_SS21_WU/all_Pre_Home_Live_CW3721_Women_clz.jpg']</value>
      <webElementGuid>c1e47b64-6a47-4d3c-9ac4-9e30fa3708dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
