<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_dwfrm_profile_login__1ac445</name>
   <tag></tag>
   <elementGuidId>f20f386a-8028-4bde-b691-d0786a5b7612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration-form-password-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-password-confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4927a123-7877-4c60-93e3-2d9c0f217f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*Confirm Password </value>
      <webElementGuid>0fd0bd4b-4707-45d3-9f76-7f75ca1bf87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>*Confirm Password </value>
      <webElementGuid>e2c4c283-6831-4b39-a3dd-d44edd4933cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>62497625-85f2-4671-8004-9a570b2a699d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-equalto</name>
      <type>Main</type>
      <value>#registration-form-password</value>
      <webElementGuid>169aa2f6-6e7c-43bf-b66f-eb78578a5726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-password-confirm</value>
      <webElementGuid>5c2d2ef9-af0e-4351-a8ee-2259ef369913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3bf63a59-87cc-4ec5-8acd-47c5377bd8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Inserisci una password.</value>
      <webElementGuid>d0e9f8e7-e95a-477b-a907-c53f65ef409a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-equalto-message</name>
      <type>Main</type>
      <value>Le password inserite non corrispondono.</value>
      <webElementGuid>7b395ca4-9777-4db2-983b-ee3fc63606a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-length-message</name>
      <type>Main</type>
      <value>Spiacenti, la password inserita non corrisponde ai requisiti.</value>
      <webElementGuid>a65db304-d52e-4e3c-9867-ebe3e9ca9336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profile_login_passwordconfirm</value>
      <webElementGuid>deb364f1-8338-45d0-b716-78db4bdaca57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6a56a936-a745-4161-a32b-cc78ecc186c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>6bc45034-0ba7-4a2b-859f-a7d57351041e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e72514f6-be9a-452f-844c-34a8a4730634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-valid-input</value>
      <webElementGuid>c8da5b0d-7ef1-44f0-bb07-20aa7cb5b486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-password-confirm&quot;)</value>
      <webElementGuid>6c25f383-f72d-4c76-bfef-3e67bd5598fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-password-confirm']</value>
      <webElementGuid>53c43f3d-8375-4db2-b962-c26d6b18f522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[2]/div[4]/div/div/form/div/div[5]/label/input</value>
      <webElementGuid>fc5c5286-1b67-431a-95ad-e9abf46d2d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/input</value>
      <webElementGuid>8be2c727-1483-401c-bfd0-088d86cb1bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '*Confirm Password ' and @title = '*Confirm Password ' and @type = 'password' and @id = 'registration-form-password-confirm' and @name = 'dwfrm_profile_login_passwordconfirm']</value>
      <webElementGuid>49f208a9-fa81-4b53-bbd2-bb686bc0354c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
