<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefono_dwfrm_profile_customer_phone</name>
   <tag></tag>
   <elementGuidId>a71f3965-6992-4c35-9e67-97bdbc381554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration-form-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a3e249a-4bd9-40b2-a3f6-18665d1fce56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>*Telefono</value>
      <webElementGuid>3c4f06a1-76a8-4a0a-ae57-de50018d4c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*Telefono</value>
      <webElementGuid>c8f5866b-193f-4adf-96e6-947697da8d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93de0df1-1289-4c22-94fd-604d82ce5a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-phone</value>
      <webElementGuid>de1debfa-1210-4b02-9f72-437db813c214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Numero non corretto.</value>
      <webElementGuid>2fc30046-48ec-411a-b660-04c75549a064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Numero non corretto.</value>
      <webElementGuid>169e9208-95c2-48d6-b98a-d89395f431e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profile_customer_phone</value>
      <webElementGuid>1bbf9b98-4f77-43e5-8307-809013e6fac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24df8b2b-6709-4e66-a234-7f904ccee699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>360b8ca0-b488-4900-bea4-431c165c941b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{5,11}</value>
      <webElementGuid>1a0c4f44-242b-48ec-abe2-c34cd6a13a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-valid-input</value>
      <webElementGuid>35ba2f82-e761-41e8-bc61-87f1ad75c391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-phone&quot;)</value>
      <webElementGuid>e3cc5188-8112-455a-8c27-00b67119746b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-phone']</value>
      <webElementGuid>fa8cdaad-eba5-4222-8177-91d4dc89c238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[2]/div[4]/div/div/div/div/form/div[3]/div[2]/label/input</value>
      <webElementGuid>1ab423ef-9cc0-49c5-afe3-e8fd26f490d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>62cbbc31-f0b3-43b1-bb48-32bbadbc0741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = '*Telefono' and @placeholder = '*Telefono' and @type = 'text' and @id = 'registration-form-phone' and @name = 'dwfrm_profile_customer_phone']</value>
      <webElementGuid>e6e95c3b-8e6f-43ca-9151-2e2ec08dffae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
