<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cognome_dwfrm_profile_customer_lastname</name>
   <tag></tag>
   <elementGuidId>d12874cf-b7a5-49d2-8b63-f868a0d5ae9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration-form-lname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-lname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>761e5870-05ee-4cf8-98e9-50266db164f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*Cognome </value>
      <webElementGuid>024019a3-7cc1-4f84-9929-f0e9647472f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>*Cognome </value>
      <webElementGuid>80f7847c-0345-404b-b95b-b2b9df9dec9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5aa96161-f85a-4613-b85e-03bf58457633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-lname</value>
      <webElementGuid>c07fb5f6-adf7-4199-b817-57c875a270ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-valid-input</value>
      <webElementGuid>c0749ce0-1b04-41b8-972e-d9acff324557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Il cognome è obbligatorio.</value>
      <webElementGuid>8c260e92-3e39-464c-92c7-dc73cdf6007d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Il cognome deve contenere da 1 a 50 caratteri e non può contenere caratteri speciali.</value>
      <webElementGuid>07b82583-4f19-4d80-9d15-8e4ef0b9523c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profile_customer_lastname</value>
      <webElementGuid>1b819119-863e-48f2-adb0-874c7c216c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39fedbfb-8706-4d15-abe1-a9e757c5e99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ea5f10b8-c935-4d32-bbca-a0efa23b7102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-ZďěťůàáâäãåąčćęèéêëėįìíîïłńňřòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĎĖĘÈĚÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚŮÛÜŲŪŸÝŤŻŹÑßÇŒÆČŠŽ∂ð '\-]*</value>
      <webElementGuid>31a6569c-f73a-4d46-9fd7-91939837b7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-lname&quot;)</value>
      <webElementGuid>71f794f4-7978-4345-b729-6b34178ea029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-lname']</value>
      <webElementGuid>de7b2e58-d16e-4c08-8241-36c2d22482cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[2]/div[4]/div/div/form/div/div[3]/label/input</value>
      <webElementGuid>d59d947e-088d-43a1-a53a-09c3d8bca4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>1842a123-639f-4bd0-af44-aa92f7b11f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '*Cognome ' and @title = '*Cognome ' and @type = 'text' and @id = 'registration-form-lname' and @name = 'dwfrm_profile_customer_lastname']</value>
      <webElementGuid>2e1c6973-7bdc-493f-b1da-e405e71cc33f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
