<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome_dwfrm_profile_customer_firstname</name>
   <tag></tag>
   <elementGuidId>8de0be6b-41c2-4b8c-a7ae-c00d5aa4e5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration-form-fname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-fname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41da84fe-edc8-4f3f-8a62-24aff4e6df0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*Nome </value>
      <webElementGuid>fe85e962-016a-4dab-9c6e-db38601000c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>*Nome </value>
      <webElementGuid>b819ee2c-c6f4-4ed5-b37b-fd99e5d6f1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff68eeee-e06a-476d-8933-7f86e6cbdd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-fname</value>
      <webElementGuid>2851e895-6edd-46c5-b89c-f42bd21dc5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-valid-input</value>
      <webElementGuid>a9787a8b-a63b-495e-bec3-1da7c09b903a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Il nome è obbligatorio.</value>
      <webElementGuid>cf856cca-9588-4adf-a0a7-1e84d7aee096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Il nome deve contenere da 1 a 50 caratteri e non può contenere caratteri speciali.</value>
      <webElementGuid>9f45e77e-bd61-4f13-89a5-1631a7c0c66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profile_customer_firstname</value>
      <webElementGuid>344e2b5f-6888-4740-a023-52fd08af28ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4c1678d-0639-4ac7-a21c-7c02f9f3448b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>076c58e0-fe13-4acc-aa9f-945befb5fb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-ZďěťůàáâäãåąčćęèéêëėįìíîïłńňřòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĎĖĘÈĚÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚŮÛÜŲŪŸÝŤŻŹÑßÇŒÆČŠŽ∂ð '\-]*</value>
      <webElementGuid>296f7e32-8d52-441a-9d98-3aab7bf80530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-fname&quot;)</value>
      <webElementGuid>8062d71f-3ea2-455b-b204-056655cf6425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-fname']</value>
      <webElementGuid>6fc51891-b570-4012-a82e-4c7df831d62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[2]/div[4]/div/div/form/div/div[2]/label/input</value>
      <webElementGuid>5ec51169-068b-4e92-97ff-8edc6eea9395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>cdd2bc3a-0edc-4755-963f-52d6b3118f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '*Nome ' and @title = '*Nome ' and @type = 'text' and @id = 'registration-form-fname' and @name = 'dwfrm_profile_customer_firstname']</value>
      <webElementGuid>94b9651d-4e98-4584-b5a7-c7c94452b837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
