<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Donna</name>
   <tag></tag>
   <elementGuidId>14b30522-9347-4fb4-9bb4-e87b7443c102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='catWoman']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.category-name-prehome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f54cfb1c-5e7a-4c1d-ab46-1d79892eaaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category-name-prehome</value>
      <webElementGuid>2e8d7b4c-323f-40cd-8e0c-246eeef4b125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Donna</value>
      <webElementGuid>0cfe98e5-4ee8-472e-a34e-b4c203ef3efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catWoman&quot;)/a[1]/span[@class=&quot;category-name-prehome&quot;]</value>
      <webElementGuid>2707ed44-8db2-489d-82ef-559568328b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e6d567c-e1a1-4d6a-99b8-f22e20deafd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category-name-prehome</value>
      <webElementGuid>49db060b-deec-4a25-af14-1b7afa6e13f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Donna</value>
      <webElementGuid>dbc02c3e-bce9-4efa-981a-d316f96f861b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catWoman&quot;)/a[1]/span[@class=&quot;category-name-prehome&quot;]</value>
      <webElementGuid>878db933-559b-490b-aa56-212abe2b4739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catWoman']/a/span</value>
      <webElementGuid>e7f0a53f-47a7-4552-a6a3-a594cfc5ee1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uomo'])[1]/preceding::span[1]</value>
      <webElementGuid>c9a188c5-b070-4237-9f9c-c53a0a3b9b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bimbi'])[1]/preceding::span[2]</value>
      <webElementGuid>b70b7ad2-73d8-4919-b84c-c636147d2988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Donna']/parent::*</value>
      <webElementGuid>6e49e58b-6dc2-4450-bbac-1055409d5fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>11579bb6-daa5-4486-bc4c-2d90426cd082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Donna' or . = 'Donna')]</value>
      <webElementGuid>a7e6f38b-7758-4832-9839-6eae8a599f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
