<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>d7476b0d-c484-469e-8423-ff7d2b262a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9aef7da-1fb5-4798-b3b6-2014c4b46ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffec295f-4cc1-4649-96e7-d26a3a3f3afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>1de3bca6-5a12-4225-ac57-4b4e696b29fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;ls-tab-off tingle-enabled&quot;]/div[@class=&quot;tingle-modal newsletter-popup tingle-modal--visible&quot;]/div[@class=&quot;tingle-modal-box&quot;]/div[@class=&quot;tingle-modal-box__content&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell medium-5&quot;]/div[@class=&quot;newsletter-popup__content&quot;]/button[@class=&quot;close&quot;]/span[1]</value>
      <webElementGuid>2342f4d5-92eb-4c75-8250-926c45571b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>882d459e-3094-443b-ae72-46948c09374c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>geoblock-close-text</value>
      <webElementGuid>be310b05-35a5-4196-a866-798e52130b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Esci</value>
      <webElementGuid>c4c9bf81-43de-4133-8e36-9d5cbd67d023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>30879635-9a14-47ab-bce8-d8855fe3a60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;geoblock-close&quot;)/span[@class=&quot;geoblock-close-text&quot;]</value>
      <webElementGuid>b53776bc-7a4a-4b70-9595-1422cf5bd0c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div/div/div/div/div[2]/div/button/span</value>
      <webElementGuid>1f894e8a-c7d5-4105-b1a1-b461ab987b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iscriviti alla nostra newsletter'])[1]/following::span[1]</value>
      <webElementGuid>39571cd8-19b0-45ec-b430-c8634b52a321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::span[1]</value>
      <webElementGuid>ef2bd678-5151-4470-9139-5e7eeefe688e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Si prega di selezionare un titolo.'])[1]/preceding::span[1]</value>
      <webElementGuid>566fe004-7010-4907-b207-02be2baf83d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>490e2b53-3a00-49d5-bd7a-31870ce18fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>dad32808-94c5-42a0-b231-50628008b02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='geoblock-close']/span</value>
      <webElementGuid>66c75da3-c7f4-48ac-9968-eed08026d9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Visita l', &quot;'&quot;, 'e-store del tuo paese')])[1]/following::span[2]</value>
      <webElementGuid>8357944a-7489-40c5-80ad-83456126a21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'geoblock-close', '&quot;', ')/span[@class=', '&quot;', 'geoblock-close-text', '&quot;', ']')])[1]/preceding::span[1]</value>
      <webElementGuid>0415b94f-7a84-40bb-bafe-ea6bad93b677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ti serve aiuto?'])[1]/preceding::span[1]</value>
      <webElementGuid>46f385a7-5161-47b1-ae65-0bb8043b2d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>0d28c0a0-9e6e-4193-be3a-aea25c897036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
