<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Seleziona l, , importo)_giftca_4448fd</name>
   <tag></tag>
   <elementGuidId>81455df1-bd61-4dac-9f28-f33613f51d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard--mail-to']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#giftcard--mail-to</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bb918a5-da7a-4630-a88a-6c8418d84635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>E-mail del destinatario</value>
      <webElementGuid>cfac9b00-e480-42a6-bb69-60d1ae255e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E-mail del destinatario</value>
      <webElementGuid>067da668-4da4-4510-9d85-2dd3eaa1831d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3aa8516-984c-46c3-a89f-33b79886c556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard--mail-to</value>
      <webElementGuid>dbe1464b-ef97-4b99-8fe1-fa870fea9892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcardMailTo</value>
      <webElementGuid>6ce8a2ca-81ab-4d96-becb-9a7a10e74d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>parsleyValidatableElement giftcardEmailTo small</value>
      <webElementGuid>fff7e7db-b25a-4fcb-8a4c-acc4eb68028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3136540b-fbce-4038-805b-46b01089b72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Inserisci una e-mail valida.</value>
      <webElementGuid>0c972384-f0ed-4244-8a86-a911d89a5f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-type-message</name>
      <type>Main</type>
      <value>Inserisci una e-mail valida.</value>
      <webElementGuid>85214af4-dd1d-4451-bbc3-bb3d500b9df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard--mail-to&quot;)</value>
      <webElementGuid>096f78f8-534e-4549-b581-2b58cdba3237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard--mail-to']</value>
      <webElementGuid>79dad93a-75fc-40ef-96b2-19580a825058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[3]/div[3]/div/div[3]/div[4]/div/div/div[5]/div/label/input</value>
      <webElementGuid>9d8c64f4-faac-438b-a8c8-ada896fd12a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label/input</value>
      <webElementGuid>6f2010d3-5274-49d9-a010-6ed06dea559d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'E-mail del destinatario' and @placeholder = 'E-mail del destinatario' and @type = 'text' and @id = 'giftcard--mail-to' and @name = 'giftcardMailTo']</value>
      <webElementGuid>718a4bf0-32a6-4f41-aafc-e48302bc6edf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
