<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Seleziona l, , importo)_giftca_313951</name>
   <tag></tag>
   <elementGuidId>d8dbf3fb-de9d-4097-aece-50eeb682b804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard--name-to']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#giftcard--name-to</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f0efd61-787f-41d2-9a43-531f7db54eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nome del destinatario</value>
      <webElementGuid>2cfdbb99-0820-48a3-a697-fe58540576d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nome del destinatario</value>
      <webElementGuid>019d7ef7-e1c6-479e-93ec-136298155467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f6cd03c-7c3c-4cbe-886e-8faa67651707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard--name-to</value>
      <webElementGuid>67e1cc69-d71d-418d-a680-7836bbf8a101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcardNameTo</value>
      <webElementGuid>3bded339-edbb-46ea-bd5a-196f2061f4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-giftcardNameTo parsleyValidatableElement small</value>
      <webElementGuid>179b45e1-c713-4e02-b1b5-09c25e4bc7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Il nome è obbligatorio.</value>
      <webElementGuid>f50b1664-94c1-4dc9-add5-3b4332bb3cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard--name-to&quot;)</value>
      <webElementGuid>3466ff5c-b93c-4882-be4d-d032e2179219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard--name-to']</value>
      <webElementGuid>0633ff0a-5f23-4c62-a88a-1b7c699980ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[3]/div[3]/div/div[3]/div[4]/div/div/div[4]/div[2]/label/input</value>
      <webElementGuid>a95fbff2-f826-4984-8279-dcaf87e0d35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label/input</value>
      <webElementGuid>8dcd2625-4720-4f75-b052-46578a242240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Nome del destinatario' and @placeholder = 'Nome del destinatario' and @type = 'text' and @id = 'giftcard--name-to' and @name = 'giftcardNameTo']</value>
      <webElementGuid>914e4c1b-55f7-469b-9794-a1a5a4806289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
