<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Seleziona l, , importo)_giftca_c4c302</name>
   <tag></tag>
   <elementGuidId>8c123468-1809-448f-8d0e-737f55768622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard--your-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#giftcard--your-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ada78bb-2b56-49cd-8f8e-276428d52fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Il tuo nome</value>
      <webElementGuid>4759d195-be33-4280-8376-121dd84e22ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Il tuo nome</value>
      <webElementGuid>e2964c9c-f6e3-4a1d-ab3a-e6cfc83f1bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>847eaf69-104a-46a9-b7a2-3ed73149870c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard--your-name</value>
      <webElementGuid>66b5e1c9-fa98-48f1-ae22-0a9a28806e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcardYourName</value>
      <webElementGuid>73552d4b-c540-4e27-b729-9ee48fd041a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-giftcardYourName parsleyValidatableElement small</value>
      <webElementGuid>0809a81e-7dff-49ae-a12c-0d4ec440a505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Il nome è obbligatorio.</value>
      <webElementGuid>1224fee6-c7bd-4924-9d78-5c7fd8ca3bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard--your-name&quot;)</value>
      <webElementGuid>34b96ae6-cfe5-4ef3-bc79-238a04ee530f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard--your-name']</value>
      <webElementGuid>470b494c-5a24-427e-b023-95870ae863d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[3]/div[3]/div/div[3]/div[4]/div/div/div[4]/div/label/input</value>
      <webElementGuid>5731a841-5128-421e-949a-6ac57e59b219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/input</value>
      <webElementGuid>c65b9cf8-45f4-40b8-bdb1-726a9b682b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Il tuo nome' and @placeholder = 'Il tuo nome' and @type = 'text' and @id = 'giftcard--your-name' and @name = 'giftcardYourName']</value>
      <webElementGuid>19e3d014-8319-488f-86b6-88aab5784f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
