<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Gift Card_typeAmount</name>
   <tag></tag>
   <elementGuidId>1848c3ef-0464-41a0-a547-fc75f2d9a4d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='typeAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;typeAmount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a53a3a61-2bbc-4919-b82e-d1f821fc4d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small js-typeAmount js-amount-selector active</value>
      <webElementGuid>fed8a85d-b81d-4ce5-839e-6fa14b608e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>376ce182-2068-4708-854a-b007be9aeb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeAmount</value>
      <webElementGuid>dd36c857-8a5b-45f5-b402-5884b03567d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Inserisci l'importo</value>
      <webElementGuid>82924556-7262-4a5c-96b8-f953ce9ace40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-amount</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf85f1e1-50f7-44a2-9d88-791f3d61c55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>30.0</value>
      <webElementGuid>471078a6-a9e3-4057-9823-02014fbd4e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>1000.0</value>
      <webElementGuid>91330396-649b-46b2-beaf-75c14ce0c26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idx</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1a5c4321-0438-4513-950a-58c3e44a9e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>30.0</value>
      <webElementGuid>370bef03-74ac-41fa-8b54-2949331b999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000.0</value>
      <webElementGuid>88981d67-e42f-436a-a25f-64eb50c6cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;ls-tab-off&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;grid-container&quot;]/div[@class=&quot;grid-x align-center&quot;]/div[@class=&quot;product-detail product-wrapper grid-x product-giftcard&quot;]/div[@class=&quot;cell large-4 medium-4 small-10 pos-relative&quot;]/div[@class=&quot;grid-y grid-margin-x&quot;]/div[@class=&quot;cell large-10&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;cell large-10 medium-10 small-10&quot;]/div[@class=&quot;grid-x grid-margin-x&quot;]/div[@class=&quot;cell small-5&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell small-10 amount-free-cell&quot;]/input[@class=&quot;small js-typeAmount js-amount-selector active&quot;]</value>
      <webElementGuid>f435eaf4-7ad5-4d92-a438-476562d27cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='typeAmount']</value>
      <webElementGuid>f1d5298f-ad88-4b5d-8a5a-ec03ae6af8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div[3]/div[3]/div/div[3]/div[4]/div/div/div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>08e622cb-1b4c-4b87-9ca3-33d2963edeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e9e8dd88-7171-4bb6-8d71-c9aa6bbd7836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'typeAmount' and @placeholder = concat(&quot;Inserisci l&quot; , &quot;'&quot; , &quot;importo&quot;)]</value>
      <webElementGuid>e8959e66-6fb1-4d8d-b3f6-d2948ad1eae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
