<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>size65C</name>
   <tag></tag>
   <elementGuidId>8bd61c7d-f6ef-404d-98d2-18734b3b7334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[3]/div/div[5]/div[4]/div/div[3]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div/label[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[3]/div/div[5]/div[4]/div/div[3]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div/label[1]/div</value>
      <webElementGuid>097bdea5-cd8b-410e-8940-48bfb47e0fb7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
