<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>exitSmartGitft</name>
   <tag></tag>
   <elementGuidId>29c5d327-d8f9-4334-92f9-19dac8621867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[10]/div/div[2]/div[2]/div[2]/div/div[1]/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>/html/body/div[10]/div/div[2]/div[2]/div[2]/div/div[1]/div/button</value>
      <webElementGuid>799d21d2-9e20-4b9c-8303-dc81dc7e04a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
