<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Si prega di selezionare un titolo_radio-input</name>
   <tag></tag>
   <elementGuidId>f9865064-9eb7-4dcf-9984-21e37614c0d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.radio-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='ext-gen44']/body/div/div/div/div/div/div/form/div/div[3]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen44&quot;)/body[@class=&quot;ls-tab-off tingle-enabled&quot;]/div[@class=&quot;tingle-modal newsletter-popup tingle-modal--visible tingle-modal--overflow&quot;]/div[@class=&quot;tingle-modal-box rightModalAttribute&quot;]/div[@class=&quot;tingle-modal-box__content&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;newsletter-popup__content&quot;]/form[@class=&quot;registerNewsletter&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell mrmrsChoice&quot;]/label[@class=&quot;boolean-field mobilePadding&quot;]/span[@class=&quot;radio-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='ext-gen44']/body/div/div/div/div/div/div/form/div/div[3]/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
   </webElementXpaths>
</WebElementEntity>
