<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome_dwfrm_shipping_shippingAddress_a_e65a55</name>
   <tag></tag>
   <elementGuidId>d6a6307c-d57e-43ba-be75-0d686b0d9cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingFirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shippingFirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1784351-0569-4d73-b7a0-670c9e6654ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3524bdde-0a3d-45c8-8b2e-7efb8e1e263e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*Nome</value>
      <webElementGuid>b0ac85fb-0c1f-4736-a913-0d9ff3b4f77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small shippingFirstName is-valid-input</value>
      <webElementGuid>3ef157d9-29a7-4a52-84fb-f8e4f3f49a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingFirstName</value>
      <webElementGuid>718211a5-a1e7-4095-b42d-259df2bd4cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Inserisci il nome</value>
      <webElementGuid>53aef8e8-d6dc-459b-a541-8ccaed69d67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Inserire un nome valido</value>
      <webElementGuid>2cc1c387-b8f0-4566-b31e-8196d5a854db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_shipping_shippingAddress_addressFields_firstName</value>
      <webElementGuid>6202b661-5b2d-4f45-8b6e-b4395d80af73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd7bd479-d996-4597-8657-3faabb93915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>03a5082a-aa2d-4f2e-943c-dab1d23ff9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[A-Za-zÀ-ÖØ-öø-ÿ\-\s']*</value>
      <webElementGuid>693e7e95-f7f8-4935-91d5-5c8945426999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>06456eec-9373-4afd-9b37-2ae59ca9fafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingFirstName&quot;)</value>
      <webElementGuid>6dfa6733-805d-4d8a-86c8-9b803c1b526d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingFirstName']</value>
      <webElementGuid>4db6c76e-dacb-4320-b938-638477a20ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shippingAddressForm']/div/div[7]/div/div/input</value>
      <webElementGuid>fb38c91e-2b7c-4dec-b0df-73327d1a833a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>4b957707-95b4-4e17-b7c8-cebecf18cf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '*Nome' and @id = 'shippingFirstName' and @name = 'dwfrm_shipping_shippingAddress_addressFields_firstName']</value>
      <webElementGuid>5e7e6a0f-154e-4560-ac11-30ea2cb6d405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
