<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cognome_dwfrm_shipping_shippingAddres_f38247</name>
   <tag></tag>
   <elementGuidId>6ed13ad1-4dbe-4099-a8b6-3324bdd3e003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingLastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shippingLastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a249a429-083e-4596-8b4e-6ff6bb0a9bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ee7312a-2f3b-4e90-8420-06986f424a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*Cognome</value>
      <webElementGuid>1cc718de-589d-49e9-b035-f59f8746113a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shippingLastName small is-valid-input</value>
      <webElementGuid>5283145c-a3fa-457a-9ea4-28c7b9984430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingLastName</value>
      <webElementGuid>dc4893d3-c274-466a-a072-597a2c7993cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Inserisci il cognome</value>
      <webElementGuid>11a6de11-24c2-4ee5-bdae-820484232521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Inserire un cognome valido</value>
      <webElementGuid>48c5b56f-265a-4dd8-aa4b-5772377444e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_shipping_shippingAddress_addressFields_lastName</value>
      <webElementGuid>3a51cc50-4323-4900-b108-8146162aae78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0e5ec5e-31f6-45dc-a0be-b5cbea20bef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fbcb6a5a-9268-40d6-bde8-0ec29875405a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[A-Za-zÀ-ÖØ-öø-ÿ\-\s']*</value>
      <webElementGuid>4b89daeb-3f18-4865-8de9-fa98dc7790e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>8abeaecc-258f-4453-8ba4-12fe3b140233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingLastName&quot;)</value>
      <webElementGuid>541bd4a6-b037-404f-920a-7d1cbe73da64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingLastName']</value>
      <webElementGuid>675accee-50b6-47e4-b16c-d48bf80fddd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shippingAddressForm']/div/div[7]/div[2]/div/input</value>
      <webElementGuid>3ff32332-003c-4856-b736-f39409880fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>bf21a671-a415-4484-90c4-ca3e7001e6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '*Cognome' and @id = 'shippingLastName' and @name = 'dwfrm_shipping_shippingAddress_addressFields_lastName']</value>
      <webElementGuid>eb3b4964-dc89-42bb-ad3f-211346e2b7f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
