<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefono_dwfrm_shipping_shippingAddre_62d755</name>
   <tag></tag>
   <elementGuidId>c83b9bd1-2144-4689-b4c7-89d8d7f346b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingPhoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shippingPhoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5c14bb4-a8a1-42eb-b8f4-7e64cb0b197d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>15bae4f5-4595-496a-9186-575002885553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8cc8f9c5-ae7f-4b8e-a289-0aa370b348c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small shippingPhoneNumber is-valid-input</value>
      <webElementGuid>8238a25b-f3a1-45dd-8738-985f309e4bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingPhoneNumber</value>
      <webElementGuid>f09ed34f-1928-4249-8f2e-3330cbd0cc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Es.: 9234567890</value>
      <webElementGuid>7d1c48e8-205d-4ad6-9d76-49ea0b4dfaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Inserisci un numero di telefono valido</value>
      <webElementGuid>0a7d8112-ee74-4c86-bb45-9f75197e0590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Numero non corretto.</value>
      <webElementGuid>582e426a-5875-4946-ae58-14b4e78ee080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_shipping_shippingAddress_addressFields_phone</value>
      <webElementGuid>04040640-69eb-4df6-81d8-223ff16a847f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0ac919c-98bc-44b5-9b88-fea2c653d080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>3532b415-9e16-4d4d-987a-9edfa1e830f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{5,11}</value>
      <webElementGuid>25f19c14-d3eb-4f94-848d-8d9ad078aac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingPhoneNumber&quot;)</value>
      <webElementGuid>bb7a9092-eb09-4be7-99e6-3faaeea64464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingPhoneNumber']</value>
      <webElementGuid>6fadcfec-eb12-4371-b354-89e81946b8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shippingAddressForm']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>49ef180f-ad4e-4e3c-b4f4-0a515b3363d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ffa3b352-ded2-4236-a8c6-c1fd7a45f239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'shippingPhoneNumber' and @placeholder = 'Es.: 9234567890' and @name = 'dwfrm_shipping_shippingAddress_addressFields_phone']</value>
      <webElementGuid>0f3d805c-6426-445e-ba31-c66ec29b153e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
