<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_dwfrm_shipping_shippingAddress_8175dc</name>
   <tag></tag>
   <elementGuidId>7f788a72-dab6-4983-a775-7eab71b13a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shippingEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e78045b8-1c0a-490f-882a-8a1f6a2ac4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18079a5d-1e82-4cbf-b7a5-a332df5dc78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*E-mail</value>
      <webElementGuid>d2cbe37c-aec5-4ec3-a64a-9222c0878b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small shippingEmail is-valid-input</value>
      <webElementGuid>6fd3d6c9-96b5-4c69-addb-d658b60c5861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingEmail</value>
      <webElementGuid>ac757f03-dd29-45c0-9ddd-610a0d74c74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Si prega di inserire un indirizzo email valido.</value>
      <webElementGuid>6e14a8b4-5b7d-40d8-84df-fd4691d91eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Si prega di inserire un indirizzo email valido.</value>
      <webElementGuid>32716129-a047-470c-bfe2-e637e1be4e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-type-message</name>
      <type>Main</type>
      <value>Si prega di inserire un indirizzo email valido.</value>
      <webElementGuid>145cd0d3-b064-4ee5-b8fb-83a827cf07a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fce569f8-74d5-44e0-a2f6-36b91e1d8443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_shipping_shippingAddress_addressFields_email</value>
      <webElementGuid>ce616905-314b-42df-888e-85b0a068288f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47665738-f368-4f32-89b3-378afa2fa9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>62693551-08a2-4f1d-9a7f-1227c5e32439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\w+([\.-]?\w+)*@[\w.-]*[\w-]\.[\w]{2,6}(?!\s)$</value>
      <webElementGuid>8ae691cf-baf3-4349-a7e9-e51d557bb8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingEmail&quot;)</value>
      <webElementGuid>feef5294-f01f-4c11-a99c-17021fb0add9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingEmail']</value>
      <webElementGuid>de700312-2ba4-40f8-a2d2-aa640421ea3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shippingAddressForm']/div/div/div/div/input</value>
      <webElementGuid>bc0ddc12-b39f-40f5-9a2b-f788a2d87016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/div/input</value>
      <webElementGuid>cf2d2657-f26b-4a0c-8471-3f279ce9e266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '*E-mail' and @id = 'shippingEmail' and @name = 'dwfrm_shipping_shippingAddress_addressFields_email']</value>
      <webElementGuid>44932a9b-7640-4660-aa53-6fa499e63e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
