<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PayPal_checkbox-input</name>
   <tag></tag>
   <elementGuidId>fdd597b6-50f7-4ce3-a80c-8e6dbb9fee09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paypal-content']/div/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paypal-content > div.policy-promotion-payment > div.grid-x > div.cell.small-10.form-group.error-inside > label.boolean-field.no-margin > span.checkbox-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c341c3c3-03da-484b-bd71-eeb690076442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input</value>
      <webElementGuid>37328cd3-d877-445d-9b39-baf5a9e1c933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypal-content&quot;)/div[@class=&quot;policy-promotion-payment&quot;]/div[@class=&quot;grid-x&quot;]/div[@class=&quot;cell small-10 form-group error-inside&quot;]/label[@class=&quot;boolean-field no-margin&quot;]/span[@class=&quot;checkbox-input&quot;]</value>
      <webElementGuid>0178fc46-1545-4e2c-89d5-3b5d988946b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paypal-content']/div/div/div/label/span</value>
      <webElementGuid>75a64028-f6f3-4952-b21b-dd956c0935b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/label/span</value>
      <webElementGuid>d2eaf82f-1023-4cd0-b9da-bde3929046a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
