<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Conferma e invia ordine_radio-input</name>
   <tag></tag>
   <elementGuidId>1e57042a-6f37-4874-bea1-ce4c4dacdfd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='dwfrm_billing']/fieldset/div[2]/ul/div[4]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd0f1632-fe5f-4b8c-8fac-504cb3486275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-input</value>
      <webElementGuid>fea97006-3e81-4552-a76a-6bd40dd79439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dwfrm_billing&quot;)/fieldset[1]/div[@class=&quot;form-nav billing-nav payment-information&quot;]/ul[@class=&quot;nav payment-options&quot;]/div[@class=&quot;drawer&quot;]/div[@class=&quot;drawer-header&quot;]/label[@class=&quot;boolean-field&quot;]/span[@class=&quot;radio-input&quot;]</value>
      <webElementGuid>a6cdc59f-74bd-4f28-afc4-179b0e972eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dwfrm_billing']/fieldset/div[2]/ul/div[4]/div/label/span</value>
      <webElementGuid>f39557f0-7f1d-4e75-a827-ac3db3e6cd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/span</value>
      <webElementGuid>c932b41e-f9a7-47c4-be31-267f6108e2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
