<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>0a870c9c-153a-427b-94ec-08d1bae20b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refresh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refresh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9ef0a6f-d341-4d59-aed1-e33f1e2e806e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refresh</value>
      <webElementGuid>bc9fcf1c-edcd-4928-9961-8091ff97f494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md but textu f36</value>
      <webElementGuid>efb43ac3-bfa6-4973-8a8a-7fc084261f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(chkl())r();</value>
      <webElementGuid>df76f98e-0829-4c45-be19-553d511a945a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>bb723822-ab25-4861-aafc-3b269d1dc37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refresh&quot;)</value>
      <webElementGuid>76dc6e33-f94c-4701-a74b-bdff52f96dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='refresh']</value>
      <webElementGuid>56d7243c-0863-4fe1-8048-e3709c4aa22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='webmail']/div/div/main/div[2]/div/div/div/div[6]/button</value>
      <webElementGuid>2e9f2e85-1158-43c7-b61b-e2c12f3ce62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::button[1]</value>
      <webElementGuid>dc3cbc90-3cbe-4933-9613-f4003615753c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::button[2]</value>
      <webElementGuid>c5a13fcf-37e3-4167-92a0-f92c716115fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::button[1]</value>
      <webElementGuid>9b5011b9-bd99-4330-aa94-a707d73631ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>a9044a92-d38f-4b0c-941a-9da234f9eceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'refresh' and (text() = '' or . = '')]</value>
      <webElementGuid>78b73f10-0a70-4542-b741-2f849b780ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
