<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newsletterX</name>
   <tag></tag>
   <elementGuidId>46a4f70a-b41f-479c-92fe-f62c7db294be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div/div[2]/div/button</value>
      <webElementGuid>24a6223b-e95a-47da-bfc5-8c622c7076c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
