<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sizeM</name>
   <tag></tag>
   <elementGuidId>994e03c3-4952-4c88-97ae-89f3b27b730e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[6]/div/div[11]/div[3]/div/div/div[4]/div[1]/span/div[1]/div[2]/div/div/div[2]/div/div/div/div/div/div/div/form/div/label[2]/span/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
